### ISSUE TITLE
password

### ISSUE THREAD

**Issue by bobce79** [Koala633/hostbase#1]
what exactly do you mean by "identify networks with possibly hexadecimal password"?

**Comment by Koala633** [comment]
> what exactly do you mean by "identify networks with possibly hexadecimal password"

Some ISP use default héxadecimal password, so if you know which ISP use hexadecimal password like 10 13 or 26 lenght password, you can set up airbase-ng cafe-latte rogue ap, no web redirection is needed, if the user entered the WPA key into your fake AP, aircrack will crack it like a WEP key with the airbase cafe-latte attack.
