### ISSUE TITLE
[hostbase-1.5FR] paquets  manquant  

### ISSUE THREAD

**Issue by dranreb38** [Koala633/hostbase#10]
Salut Flow,
J'ai toujours des problèmes d'installation de paquets manquant pour l'installation de hostbase **Kali 2022.2 Update OK**
`#  lsb_release -a

No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.2
Codename:       kali-rolling
`

`apt-get install -y build-essential upgrade-system subversion wget g++ iptables iptables-dev pavucontrol ffmpeg sqlite3 libsqlite3-dev libssl-dev libnl-3-dev libnl-genl-3-dev dsniff hostapd isc-dhcp-server pkg-config xterm freeradius apache2 php libapache2-mod-php php-mcrypt php-cli tcpdump scapy vokoscreen wireshark python-twisted bridge-utils devscripts gengetopt autoconf libtool make

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
Note : sélection de « python3-scapy » au lieu de « scapy »
Aucune version du paquet php-mcrypt n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

E: Impossible de trouver le paquet iptables-dev
E: Le paquet « php-mcrypt » n'a pas de version susceptible d'être installée
E: Impossible de trouver le paquet python-twisted
E: Le paquet « ruby-gtk2 » n'a pas de version susceptible d'être installée

┌──(root㉿kali-dell)-[/tmp]
└─# **ruby hostbase.rb
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gtk2 (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from hostbase.rb:2:in `<main>'**

mon sourcelist `: deb http://http.kali.org/kali kali-rolling main contrib non-free
`
`disquette :)

**Comment by Koala633** [comment]
Salut Disquette,

J'ai aussi eu des problèmes en faisant une maj vers kali 2022.2 mais pas exactement les memes erreurs car j'avais tout d'installé depuis un moment.Ton retour est intéréssant et va peut-etre me permettre de mettre a jour la procédure d'installation.En premier on va faire un petit nettoyage avant que tu relance l'installation avec:

`apt autoremove`

Ensuite relance l'installation en enlevant **iptables-dev php-mcrypt** et enfiin **python twisted** il se peut que ces derniers soient devenus obsolètes et non utiles.Au final ça te fait donc ça a installer.

**1 -Entrer ça dans une console:**
`apt-get install -y build-essential upgrade-system subversion wget g++ iptables pavucontrol ffmpeg sqlite3 libsqlite3-dev libssl-dev libnl-3-dev libnl-genl-3-dev dsniff hostapd isc-dhcp-server pkg-config xterm freeradius apache2 php libapache2-mod-php php-cli tcpdump python3-scapy vokoscreen wireshark bridge-utils devscripts gengetopt autoconf libtool make
`
Ensuite pour l'erreur au lancement de hostbase c'est du aux modules servant a l'interface graphique qui ne sont pas installés.Lors de la mise a jour vers kali 2022.2 j'ai eu aussi tous mes "gem" de ruby qui ont sautés, j'ai pas compris pourquoi mais bon j'ai du réinstaller le tout.

**2 -Réinstaller les ruby gem et gtk2 servant a l'interface graphique: (c'est très important de respecter l'ordre)**
```
apt-get install ruby
apt-get install ruby-dev
gem install highline
gem install rake
gem install bundler
gem install colorize
apt-get install libgtk2.0-dev
apt install gobject-introspection
apt install ruby-gtk2
```


Fais moi signe si tu as d'autres erreurs, c'est important et ça servira pour régler et actualiser les problèmes rencontrés.

**Comment by dranreb38** [comment]
Salut, 
Pour l'installation j'ai bien virer  **iptables-dev php-mcrypt** et **python twisted**  mais pas **apt autoremove**  avant.
Je te fais un retour !, ton sourcelist est celui de base de Kali2022-2 ?
@+

**Comment by Koala633** [comment]
Coucou,

**apt autoremove**  n'est pas un paquet, c'est un utilitaire de paquets qui sert a "nettoyer" un peu le systeme.Je t'ai donné cette commande pour etre sur de faire une install sur du propre.

Oui c'est le meme sourcelist mais je pense qu'il y a pas de problème avec le source.list, les paquets:
`iptables-dev php-mcrypt python twisted`

n'existent plus et certains ont changés de nom comme tu peux le voir avec scapy dans le retour de ta console:
`Note : sélection de « python3-scapy » au lieu de « scapy »`

Si ces paquets sont devenus obsolètes ou n'existent plus c'est normal qu'ils renvoient des erreurs lors de l'installation.Heureusement ils ne sont pas indispensables a l'utilisation de hostbase mais pour une configuration plus avancée: (apache2 SSL et sniff avec sslstrip).

iptables-dev était indispensable mais apparemment maintenant le paquet **iptables** tout court suffit.

**Comment by dranreb38** [comment]
> **apt autoremove** n'est pas un paquet, c'est un utilitaire de paquets qui sert a "nettoyer" un peu le systeme.Je t'ai donné cette commande pour etre sur de faire une install sur du propre.
:smiley: oui , oui je sais !

**Comment by Koala633** [comment]
D'accord :)

**Comment by dranreb38** [comment]
Bon y'a du mieux !
J'ai bien lancé
`apt autoremove`
Ensuite de nouveau étape **1**
`apt-get install -y build-essential upgrade-system subversion wget g++ iptables pavucontrol ffmpeg sqlite3 libsqlite3-dev libssl-dev libnl-3-dev libnl-genl-3-dev dsniff hostapd isc-dhcp-server pkg-config xterm freeradius apache2 php libapache2-mod-php php-cli tcpdump python3-scapy vokoscreen wireshark bridge-utils devscripts gengetopt autoconf libtool make `

Résultat **OK** !
Etape 2 
Par contre j'ai lancé **un par un** l'install et pas un copier / coller des paquets !
`
apt-get install ruby
apt-get install ruby-dev
gem install highline
gem install rake
gem install bundler
gem install colorize
apt-get install libgtk2.0-dev
apt install gobject-introspection
apt install ruby-gtk2
`

Toujours problème avec `apt install ruby-gtk2` du coup j'ai fais `gem install ruby-gtk2` cela semble **OK**

Au lancement de hostbase 
![Sélection_002](https://user-images.githubusercontent.com/16446911/180645895-b920cfbc-72ef-4687-b9b3-b4622852b406.png)
Erreur fail to load module "gail" surement manquante , mais un gem install gail ne donne rien
J'ai aussi une erreur dans la demande de scan réseau

![Sélection_003](https://user-images.githubusercontent.com/16446911/180646029-db01ae35-4819-4ae7-800c-db44e30959f3.png)

Que faut-il mettre dans l'onglet scan réseau rubrique 5GHz le canal, la fréquence ?

**Comment by Koala633** [comment]
Re,

Pour le module "gail" ça a l'air d'etre une dépendance lié a gtk plutot qu'un gem mais c'est la première fois que je vois ça, je vais regarder ça.

Pour la seconde erreur: la carte wifi pour le scan de réseau a été correctement vérifiée c'est au niveau du choix du scan en 5GHz que ça bloque.Il faut rentrer **oui** ou **non**  en minuscule dans l'entrée prévu pour.(En vérifiant bien que si tu mets **oui** wlan1 doit etre compatible 5GHz comme la 36ACH par exemple.

![aaa1](https://user-images.githubusercontent.com/26505001/180646697-f3890b06-49ef-4d47-8ddd-f2ded01afac2.png)

Si l'erreur persiste, va dans le dossier /tmp/hostbase-1.5FR et donne moi le contenu du fichier "carte.txt" et "ghz.txt".Infos a ne pas oublier: assure toi bien de copier le dossier hostbase-1.5FR dans **/tmp** et de se placer dans **/tmp/hostbase-1.5FR** pour lancer hostbase.

**Comment by dranreb38** [comment]
C'est bon avec oui dans l’onglet 5GHz, j'avais essayé yes, no, ok, canal .... :disappointed_relieved:
je t'ai envoyé un mail sur ton adresse perso :blush:
