### ISSUE TITLE
recogida de clave cle.txt

### ISSUE THREAD

**Issue by dynyly** [Koala633/hostbase#3]
salu2
decir que la recogida de claves en el archivo cle.txt
si una victima introduce varias veces clave no detecta segundo intento y copia clave seguida a anterior puede ser lio a la hora de resolver clave 
----
por otra parte si le direras opcion de recogida de pin a la livebox seria genial yo lo he hecho ....

**Comment by Koala633** [comment]
Hola :) 

Pensaba que te habia ido de la tema :D me hacer plazer de ver te aqui, no tengo nada encontra de ti :) 

> decir que la recogida de claves en el archivo cle.txt
> si una victima introduce varias veces clave no detecta segundo intento y copia clave seguida a anterior puede ser lio a la hora de resolver clave


Te creo pero eso no me lo hace... pero bueno me parece bien si lo has areglado.

> por otra parte si le direras opcion de recogida de pin a la livebox seria genial yo lo he hecho ....

Lo haré para la proxima revision.Vengo de salir una nueva revision... y me ha dado vastante tiempo.La nueva revision esta en la carpeta hostbase (no la del inglès).Despuès de descargar la carpeta, entra a dentro y copia la carpeta de hostbase dondé quieras y initia la installacion con 

`bash newinstall.sh` 

Changelog de la revision:


> Trap anaidio para salir del script con ctrl+c si tener que usar todo el tiempo la opcion "Salir"
> La carpeta de trabajo esta ahora /tmp en ve de /root antes
> Un script solo para la instalacion en ve de 2 antes (kali/ubuntu)
> Configuracion automatica de apache2
> Network-manager se inicia a la salida del script
> Anadido interfaz que system.d  llama wlx* 
> Ataque DoS el los canal lo mas usado para desconectar el usario si el punto de acceso cambia de canal (1 6 11)


No he salido la revision en wifi-libre porqué no tengo las falsas paginas todavia, lo haré cuando tendré eso.No paso muchas veces por aqui, si tienes preguntas o asi venga a wifi-libre.


++
