### ISSUE TITLE
AWUS1900 compatibility?

### ISSUE THREAD

**Issue by hista** [Koala633/hostbase#7]
Hi,
Are the 2 described attacks, airbase-ng and hostapd, compatible with an AWUS1900 wifi card?
I've read various answers about that and maybe you guys have the answer before I buy it :)

Best regards

**Comment by kcdtv** [comment]
Yes it can: [https://www.wifi-libre.com/topic-1324-hostapd-banda-5ghz-soporte-ac-con-88xxau-awuso36ach-awus1900.html](url)
But you might need to do manually some configurations as the dirver used is not official and has some tricks. For example it is not compatible with airmon-ng so the interface created in monitor mode is not named by wlanXmon. But overall it works quite good.
